language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ohp6bzaCcDbBGLNnLJ3EcbiXCXZVdSrU5wkK/erYFAdx9tqZHcXsToulE0q9nbXrljRcet1X3qKIraXliwcklcpfnMEE7caw9dkR06tBo+R2NNNuwapjYMCRnzL0j1y5xC/5DVJn8nGm27+RH3QN8KDTijKVvCQP+RXyKSxjm+RVTbPLk0S/q8GNBGWL9acd1VGFPiIFkCjzJEI6HOf1FrW04NkvLotCwXvvp6LVAaK1VYJBzsqgKkShW2qL/+RbGG5v+LmNXSPSDVw4ZVBunYQNKdFazP8ttbJWESNrtqWbVfJos+vcH8FTeGtl+9h6YCgBqbjaWWFKf05O8YS1WXkGpRztCaoiOmw8PPaUacGYypjOhqLk8pCN7A39nE9396NgSpecBGBw/g/Nr4JFDGuAkIYjtbkbvUo+nQpHBSYJUGRtsvA9BcqM8agLiEl90EnxBDxKrq+hQxI4b8AfpIyrzfCFd0c+M5BeULuhFvOXmsSRwp6lbHQJNgvazAgsffdoMN3qKDrEfAzGAZ1N5fySuf1po0h4YTS5bdlvjch8ln0MWpWSuCB1razIWzCKbi8anbh01ROUUtzg4uyKQmysMnyOaH6SoKHczWL5/2j286GUKPO3iQ4zgFjh9s8Y6tU3Scorj8znXPGEn5AA66esrpSs2wH4JZvj97ZMcOk=
  app: react-hot-cold
  on:
    repo: oscaralexander2125/react-hot-cold
