language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: IbIZUX8X6CWpvO5KYZUh+GoFVh8D7mdice0Jwvq8gLEtlILx+Faj6j6k4sG05w9vbjWZ92T4Dqz5FYKRSFbB9TfXYXaN/uve9ixojrsLa1k3z2Z4h8z7jrvBJIt/YUynefTwPghI1OTp+TdhpoavgyB3AjLH2URdveS6AEdsLkMj+Nssgo5Jd0maknRA2Py0aACr1at+iKz+wbNzUMr7a7vZyJDRZPLEJESQ7K42uzd+VeKBZe4Wibzz7i7d7zAJ3tgdGRqFfoLfyX4mGE2LeAPPpX5z3Pvp48obVxZUL5SCBRGUUU2r2sNPdAH5fE/xYPCHJI0ZuOrFElZ69qCx4yp7Alk8KTghh+hme1/SwauN6oD26A/EQB4XzZcxG01xxTiP6dRKDbcUEERemBM56u8WmrSzP4OxMTCUXpBfpUrVmN6iN3cICCk2DY6085gnYr2I4Eft9r/2OkNDN6u1/7OV6HdovuYk2Q82IACUugUKSa6LcEha5LXB0C8n2aD9mV1JZ3mPRJHuhd3ujdWrgOhb4yakrngH5pT/trgPj3/rq1WoSLl//3KwT3JWookinGhz7yNMGS44p55Bx1TC+r6DoojVgiLxeEDSRvkf3zeIIdpPhWl+2AKHFupiaJYQtSESKf2Hw6BR9aypHKSdlJ+vEViQl2TifXD6v7eLoDQ=
  app: vast-peak-28107
  on:
    repo: oscaralexander2125/react-hot-cold
